In [225]:
import pandas as pd

In [226]:
import chardet
import pandas as pd

with open('SensorData.csv', 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large

sensor=pd.read_csv('SensorData.csv', encoding=result['encoding'])

In [227]:
sensor.columns

Index(['Timestamp', 'Temperature', 'Moisture', 'Nitrogen', 'Phosphorous',
       'Potassium', 'pH', 'ElectricalConductivity'],
      dtype='object')

In [228]:
sensor=sensor[['Temperature', 'Moisture', 'Nitrogen', 'Phosphorous',
       'Potassium', 'pH', 'ElectricalConductivity']]

In [229]:
sensor

,Temperature,Moisture,Nitrogen,Phosphorous,Potassium,pH,ElectricalConductivity
0,23.9,0.0,0.0,0.0,0.0,7.00,0.0
1,23.6,13.7,26.0,36.0,73.0,7.00,369.0
2,23.6,13.8,26.0,36.0,73.0,7.00,369.0
3,23.6,13.6,26.0,36.0,73.0,7.00,366.0
4,23.6,13.7,26.0,36.0,73.0,7.00,369.0
...,...,...,...,...,...,...,...
2309,25.1,6553.5,16.0,23.0,48.0,655.35,65535.0
2310,25.1,4.6,16.0,23.0,47.0,655.35,237.0
2311,25.1,6553.5,16.0,23.0,47.0,655.35,65535.0
2312,25.1,4.4,17.0,23.0,46.0,655.35,235.0
2313,6553.5,4.2,17.0,24.0,47.0,7.00,237.0

In [230]:
sensor = sensor.dropna(how='any',axis=0)
sensor

,Temperature,Moisture,Nitrogen,Phosphorous,Potassium,pH,ElectricalConductivity
0,23.9,0.0,0.0,0.0,0.0,7.00,0.0
1,23.6,13.7,26.0,36.0,73.0,7.00,369.0
2,23.6,13.8,26.0,36.0,73.0,7.00,369.0
3,23.6,13.6,26.0,36.0,73.0,7.00,366.0
4,23.6,13.7,26.0,36.0,73.0,7.00,369.0
...,...,...,...,...,...,...,...
2309,25.1,6553.5,16.0,23.0,48.0,655.35,65535.0
2310,25.1,4.6,16.0,23.0,47.0,655.35,237.0
2311,25.1,6553.5,16.0,23.0,47.0,655.35,65535.0
2312,25.1,4.4,17.0,23.0,46.0,655.35,235.0
2313,6553.5,4.2,17.0,24.0,47.0,7.00,237.0

In [231]:
sensor.reset_index(inplace=True, drop=True)
sensor

,Temperature,Moisture,Nitrogen,Phosphorous,Potassium,pH,ElectricalConductivity
0,23.9,0.0,0.0,0.0,0.0,7.00,0.0
1,23.6,13.7,26.0,36.0,73.0,7.00,369.0
2,23.6,13.8,26.0,36.0,73.0,7.00,369.0
3,23.6,13.6,26.0,36.0,73.0,7.00,366.0
4,23.6,13.7,26.0,36.0,73.0,7.00,369.0
...,...,...,...,...,...,...,...
2252,25.1,6553.5,16.0,23.0,48.0,655.35,65535.0
2253,25.1,4.6,16.0,23.0,47.0,655.35,237.0
2254,25.1,6553.5,16.0,23.0,47.0,655.35,65535.0
2255,25.1,4.4,17.0,23.0,46.0,655.35,235.0
2256,6553.5,4.2,17.0,24.0,47.0,7.00,237.0

In [232]:
lst=[]
for i in range(len(sensor)):
    lst.append(float(sensor['Temperature'][i]))
lst

[23.9,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.6,
 23.5,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 6553.5,
 23.3,
 23.3,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.5,
 22.5,
 22.5,
 22.5,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 6553.5,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 6553.5,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 6553.5,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 6553.5,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 6553.5,
 6553.5,
 6553.5,
 6553.5,
 6553.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 6553.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 6553.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 6553.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.5,
 23.6,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 6553.5,
 23.9,
 6553.5,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 ...]

In [233]:
lst1=[]
for i in range(len(sensor)):
    lst1.append(sensor['Moisture'][i])
lst1

[0.0,
 13.7,
 13.8,
 13.6,
 13.7,
 13.7,
 13.7,
 13.5,
 13.6,
 13.8,
 13.8,
 13.7,
 13.6,
 13.7,
 13.6,
 13.7,
 13.5,
 13.6,
 13.6,
 13.7,
 13.6,
 13.6,
 13.6,
 13.6,
 13.5,
 13.6,
 13.4,
 13.6,
 13.6,
 13.7,
 13.6,
 13.6,
 13.6,
 13.7,
 13.5,
 13.5,
 13.6,
 13.7,
 13.7,
 13.6,
 13.6,
 13.6,
 13.7,
 13.7,
 13.6,
 13.5,
 13.8,
 13.6,
 13.6,
 13.4,
 13.7,
 13.5,
 13.5,
 13.6,
 13.5,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.4,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.8,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 13.6,
 8.1,
 8.5,
 8.2,
 8.2,
 8.4,
 8.5,
 8.5,
 8.3,
 8.8,
 8.5,
 8.4,
 8.6,
 8.8,
 8.5,
 8.6,
 8.5,
 8.6,
 8.6,
 8.6,
 8.5,
 8.7,
 8.3,
 8.5,
 8.4,
 8.7,
 8.8,
 8.8,
 8.5,
 8.6,
 8.4,
 8.7,
 8.6,
 8.5,
 8.8,
 8.9,
 8.9,
 8.9,
 8.5,
 8.7,
 8.8,
 8.4,
 8.4,
 8.7,
 7.8,
 8.0,
 8.2,
 8.3,
 8.0,
 8.3,
 8.3,
 8.5,
 8.4,
 8.6,
 8.3,
 8.2,
 8.3,
 8.6,
 8.4,
 8.0,
 8.3,
 8.3,
 8.3,
 8.3,
 8.1,
 8.3,
 8.3,
 8.5,
 8.3,
 8.2,
 8.3,
 8.3,
 8.1,
 8.3,
 8.4,
 8.4,
 8.2,
 8.1,
 8.3,
 8.3,
 8.3,
 8.3,
 8.3,
 8.3,
 8.3,
 8.2,
 8.3,
 8.2,
 8.3,
 8.0,
 8.0,
 8.2,
 8.6,
 8.1,
 8.0,
 8.0,
 8.2,
 8.0,
 8.2,
 8.3,
 8.6,
 8.3,
 8.0,
 8.3,
 8.4,
 8.3,
 8.2,
 8.0,
 8.3,
 8.2,
 8.1,
 8.2,
 8.2,
 7.9,
 8.3,
 8.3,
 8.3,
 8.0,
 8.3,
 8.3,
 8.2,
 8.2,
 8.0,
 8.3,
 8.3,
 8.2,
 8.1,
 8.3,
 8.2,
 8.1,
 7.7,
 8.3,
 8.4,
 8.3,
 8.5,
 8.2,
 8.3,
 8.5,
 8.0,
 8.2,
 8.4,
 8.2,
 8.4,
 8.3,
 8.3,
 8.6,
 8.2,
 8.3,
 8.0,
 8.3,
 8.3,
 8.4,
 8.3,
 8.2,
 8.3,
 8.5,
 8.4,
 8.3,
 8.2,
 8.4,
 8.3,
 8.2,
 8.4,
 8.4,
 8.3,
 8.3,
 8.2,
 8.3,
 8.0,
 8.2,
 8.3,
 8.0,
 8.2,
 8.3,
 8.2,
 8.0,
 8.2,
 8.1,
 8.0,
 8.1,
 8.2,
 8.0,
 8.3,
 8.2,
 8.2,
 8.3,
 8.3,
 8.2,
 8.3,
 8.3,
 8.2,
 8.1,
 8.3,
 8.1,
 8.0,
 8.6,
 8.1,
 8.4,
 8.3,
 8.2,
 8.2,
 8.5,
 8.0,
 8.3,
 8.3,
 8.3,
 7.9,
 8.3,
 8.4,
 8.3,
 8.4,
 8.5,
 8.0,
 8.4,
 8.2,
 8.3,
 8.3,
 8.3,
 8.3,
 8.4,
 8.2,
 8.0,
 8.3,
 8.2,
 8.5,
 8.2,
 8.2,
 8.1,
 8.0,
 8.0,
 8.4,
 8.0,
 8.3,
 8.2,
 8.0,
 8.2,
 8.2,
 8.0,
 8.0,
 8.3,
 8.1,
 8.2,
 8.0,
 8.3,
 8.4,
 8.2,
 8.2,
 8.1,
 8.4,
 8.3,
 8.1,
 8.3,
 8.3,
 8.2,
 0.0,
 12.6,
 12.8,
 12.7,
 12.7,
 12.6,
 12.7,
 12.7,
 12.7,
 12.7,
 12.7,
 12.7,
 12.7,
 12.8,
 12.9,
 12.8,
 12.7,
 12.7,
 12.7,
 12.7,
 12.7,
 12.8,
 12.9,
 12.7,
 12.7,
 7.5,
 8.0,
 7.9,
 7.8,
 8.1,
 8.1,
 7.9,
 8.0,
 8.0,
 8.3,
 8.0,
 8.1,
 0.0,
 0.0,
 0.0,
 14.5,
 14.6,
 14.6,
 14.6,
 14.7,
 14.6,
 14.5,
 14.5,
 14.6,
 14.6,
 14.6,
 14.7,
 14.6,
 14.5,
 14.5,
 14.7,
 14.7,
 14.7,
 14.6,
 14.7,
 14.7,
 14.5,
 14.7,
 14.7,
 14.5,
 14.7,
 14.7,
 14.5,
 14.6,
 14.8,
 14.7,
 14.7,
 14.8,
 14.7,
 14.5,
 14.7,
 14.6,
 14.6,
 14.6,
 14.5,
 14.6,
 14.7,
 14.7,
 14.6,
 14.8,
 14.5,
 14.7,
 14.6,
 14.6,
 14.7,
 14.8,
 14.6,
 14.6,
 14.7,
 14.5,
 14.7,
 14.8,
 14.6,
 14.6,
 14.7,
 14.6,
 14.7,
 14.6,
 14.8,
 14.8,
 14.7,
 14.6,
 14.6,
 14.6,
 14.8,
 14.8,
 14.7,
 14.8,
 14.6,
 14.7,
 14.8,
 14.6,
 14.6,
 14.7,
 14.7,
 14.6,
 14.5,
 14.7,
 14.7,
 14.6,
 14.7,
 14.8,
 14.7,
 14.6,
 14.7,
 14.5,
 14.7,
 14.5,
 14.7,
 14.8,
 14.7,
 14.7,
 14.6,
 14.6,
 14.6,
 14.7,
 14.6,
 14.8,
 14.7,
 14.5,
 14.6,
 14.7,
 14.7,
 14.5,
 14.8,
 14.6,
 14.6,
 14.6,
 14.7,
 14.7,
 14.6,
 14.8,
 14.7,
 14.5,
 14.6,
 14.5,
 14.5,
 14.6,
 14.6,
 14.7,
 14.6,
 14.6,
 14.7,
 14.7,
 14.6,
 14.8,
 14.5,
 14.6,
 14.6,
 14.6,
 14.6,
 14.7,
 14.6,
 14.6,
 14.8,
 14.6,
 14.6,
 14.7,
 14.8,
 14.6,
 14.7,
 14.7,
 14.6,
 14.6,
 14.7,
 14.6,
 14.6,
 14.6,
 14.8,
 14.5,
 14.6,
 14.7,
 14.6,
 14.8,
 14.6,
 14.6,
 14.6,
 14.5,
 14.6,
 14.6,
 14.6,
 14.7,
 14.6,
 14.7,
 14.6,
 14.7,
 14.6,
 14.7,
 14.7,
 14.8,
 14.6,
 14.7,
 14.6,
 14.6,
 14.5,
 14.8,
 14.7,
 14.7,
 14.6,
 14.5,
 14.8,
 14.7,
 14.7,
 14.6,
 14.6,
 14.5,
 14.8,
 14.7,
 14.5,
 14.7,
 14.7,
 14.6,
 14.6,
 14.7,
 14.7,
 14.8,
 14.7,
 14.8,
 14.5,
 14.7,
 14.7,
 14.8,
 14.5,
 14.5,
 14.6,
 14.5,
 14.5,
 14.5,
 14.6,
 14.7,
 14.7,
 14.8,
 14.6,
 14.6,
 14.6,
 14.5,
 14.6,
 14.5,
 14.7,
 14.7,
 14.6,
 14.6,
 14.6,
 14.5,
 14.6,
 14.8,
 14.5,
 14.5,
 14.6,
 14.7,
 14.6,
 14.7,
 14.7,
 14.7,
 14.7,
 14.3,
 14.5,
 14.6,
 14.5,
 14.5,
 14.7,
 14.7,
 14.7,
 14.6,
 14.7,
 14.8,
 14.8,
 14.6,
 14.5,
 14.6,
 14.7,
 14.7,
 14.8,
 14.6,
 14.7,
 14.8,
 14.8,
 14.6,
 14.7,
 14.6,
 14.6,
 14.6,
 14.7,
 14.8,
 14.6,
 14.6,
 14.6,
 14.8,
 14.8,
 14.9,
 14.7,
 14.7,
 14.7,
 14.8,
 14.8,
 14.8,
 14.6,
 14.6,
 14.7,
 14.5,
 14.5,
 14.6,
 14.7,
 14.6,
 14.8,
 14.7,
 14.7,
 14.6,
 14.7,
 14.8,
 14.8,
 14.8,
 14.7,
 14.6,
 14.5,
 14.7,
 14.6,
 14.7,
 14.7,
 14.7,
 14.5,
 14.7,
 14.6,
 14.5,
 14.7,
 14.7,
 14.5,
 14.5,
 14.5,
 14.5,
 14.7,
 14.7,
 14.7,
 14.5,
 14.7,
 14.5,
 14.5,
 14.5,
 14.6,
 14.5,
 14.7,
 14.7,
 14.5,
 14.6,
 6553.5,
 6553.5,
 6553.5,
 6553.5,
 6553.5,
 14.3,
 14.4,
 14.5,
 14.6,
 14.4,
 14.6,
 14.6,
 14.5,
 14.5,
 14.7,
 14.5,
 14.6,
 14.5,
 14.7,
 14.5,
 14.5,
 14.5,
 14.5,
 14.5,
 14.6,
 14.7,
 14.6,
 14.6,
 14.6,
 14.6,
 14.5,
 14.4,
 14.4,
 14.6,
 14.4,
 14.5,
 14.6,
 14.6,
 14.4,
 14.4,
 14.4,
 14.5,
 14.7,
 14.5,
 14.5,
 14.5,
 14.5,
 14.6,
 14.3,
 14.5,
 14.6,
 14.6,
 14.6,
 14.5,
 14.4,
 14.5,
 14.5,
 14.4,
 14.4,
 14.7,
 14.6,
 14.4,
 14.6,
 14.4,
 14.5,
 14.4,
 14.7,
 14.5,
 14.5,
 14.6,
 14.5,
 14.3,
 14.4,
 14.6,
 14.6,
 14.6,
 14.4,
 14.5,
 14.7,
 14.4,
 14.5,
 14.6,
 14.4,
 14.5,
 14.5,
 14.3,
 14.4,
 14.5,
 14.5,
 14.4,
 14.5,
 14.5,
 14.4,
 14.5,
 14.5,
 14.5,
 14.5,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.6,
 14.4,
 14.6,
 14.5,
 14.5,
 14.4,
 14.4,
 14.5,
 14.4,
 14.5,
 14.4,
 14.5,
 14.5,
 14.4,
 14.4,
 14.7,
 14.4,
 14.7,
 14.4,
 14.6,
 14.4,
 14.6,
 14.5,
 14.5,
 14.5,
 14.5,
 14.4,
 14.3,
 14.5,
 14.5,
 14.6,
 14.6,
 14.4,
 14.4,
 14.7,
 14.4,
 14.4,
 14.6,
 14.5,
 14.5,
 14.6,
 14.4,
 14.5,
 14.4,
 14.5,
 14.4,
 14.6,
 14.5,
 14.5,
 14.5,
 14.4,
 14.7,
 14.4,
 14.6,
 14.7,
 14.5,
 14.6,
 14.6,
 14.3,
 14.4,
 14.5,
 14.4,
 14.3,
 14.4,
 14.4,
 14.4,
 14.3,
 14.5,
 14.4,
 14.4,
 14.4,
 14.4,
 14.5,
 14.4,
 14.4,
 14.5,
 14.4,
 14.4,
 14.6,
 14.4,
 14.5,
 14.7,
 14.4,
 14.6,
 14.6,
 14.4,
 14.5,
 14.5,
 14.6,
 14.6,
 14.7,
 14.5,
 14.4,
 14.4,
 14.6,
 14.4,
 14.7,
 14.5,
 14.7,
 14.4,
 14.6,
 14.4,
 14.6,
 14.6,
 14.5,
 14.7,
 14.4,
 14.4,
 14.7,
 14.5,
 14.6,
 14.6,
 14.4,
 14.5,
 14.6,
 14.5,
 14.6,
 14.5,
 14.4,
 14.6,
 14.6,
 14.5,
 14.5,
 14.4,
 14.5,
 14.5,
 14.6,
 14.4,
 14.4,
 14.3,
 14.4,
 14.5,
 14.5,
 14.6,
 14.5,
 14.7,
 14.5,
 14.5,
 14.4,
 14.5,
 14.4,
 14.4,
 14.5,
 14.5,
 14.4,
 14.3,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.5,
 14.5,
 14.4,
 14.4,
 14.4,
 14.6,
 14.4,
 14.4,
 14.5,
 14.5,
 14.3,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.5,
 14.4,
 14.4,
 14.4,
 14.4,
 14.5,
 14.3,
 14.4,
 14.5,
 14.4,
 14.3,
 14.4,
 14.4,
 14.4,
 14.4,
 14.4,
 14.2,
 14.5,
 14.5,
 14.4,
 14.4,
 14.4,
 14.3,
 14.4,
 14.5,
 ...]

In [234]:
lst2=[]
for i in range(len(sensor)):
    lst2.append(sensor['pH'][i])
lst2

[7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.11,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.0,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.13,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 6.89,
 6.87,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 6.85,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 7.12,
 655.35,
 655.35,
 655.35,
 655.35,
 655.35,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 ...]

In [235]:
lst3=[]
for i in range(len(sensor)):
    lst3.append(sensor['ElectricalConductivity'][i])
lst3

[0.0,
 369.0,
 369.0,
 366.0,
 369.0,
 368.0,
 369.0,
 369.0,
 366.0,
 370.0,
 367.0,
 369.0,
 369.0,
 368.0,
 369.0,
 367.0,
 369.0,
 367.0,
 369.0,
 366.0,
 369.0,
 369.0,
 368.0,
 369.0,
 366.0,
 367.0,
 369.0,
 368.0,
 369.0,
 365.0,
 367.0,
 369.0,
 369.0,
 369.0,
 367.0,
 367.0,
 367.0,
 363.0,
 369.0,
 365.0,
 367.0,
 365.0,
 368.0,
 369.0,
 365.0,
 368.0,
 367.0,
 367.0,
 367.0,
 369.0,
 365.0,
 368.0,
 368.0,
 366.0,
 365.0,
 371.0,
 368.0,
 368.0,
 365.0,
 365.0,
 366.0,
 367.0,
 366.0,
 366.0,
 368.0,
 368.0,
 369.0,
 366.0,
 367.0,
 367.0,
 367.0,
 369.0,
 367.0,
 367.0,
 368.0,
 369.0,
 367.0,
 369.0,
 367.0,
 365.0,
 417.0,
 417.0,
 418.0,
 416.0,
 421.0,
 418.0,
 416.0,
 417.0,
 420.0,
 416.0,
 416.0,
 416.0,
 418.0,
 416.0,
 416.0,
 415.0,
 416.0,
 416.0,
 416.0,
 418.0,
 417.0,
 416.0,
 417.0,
 416.0,
 418.0,
 418.0,
 415.0,
 418.0,
 419.0,
 417.0,
 415.0,
 415.0,
 416.0,
 415.0,
 415.0,
 418.0,
 416.0,
 419.0,
 417.0,
 418.0,
 419.0,
 415.0,
 415.0,
 419.0,
 417.0,
 418.0,
 416.0,
 420.0,
 419.0,
 419.0,
 414.0,
 418.0,
 416.0,
 418.0,
 417.0,
 415.0,
 417.0,
 418.0,
 416.0,
 416.0,
 417.0,
 415.0,
 418.0,
 416.0,
 416.0,
 419.0,
 416.0,
 414.0,
 416.0,
 417.0,
 416.0,
 416.0,
 416.0,
 415.0,
 418.0,
 418.0,
 416.0,
 416.0,
 417.0,
 418.0,
 418.0,
 416.0,
 418.0,
 418.0,
 418.0,
 418.0,
 416.0,
 416.0,
 416.0,
 416.0,
 418.0,
 416.0,
 417.0,
 417.0,
 417.0,
 418.0,
 416.0,
 419.0,
 416.0,
 419.0,
 418.0,
 416.0,
 418.0,
 416.0,
 418.0,
 416.0,
 417.0,
 414.0,
 417.0,
 418.0,
 419.0,
 416.0,
 416.0,
 418.0,
 417.0,
 416.0,
 416.0,
 418.0,
 416.0,
 417.0,
 415.0,
 417.0,
 416.0,
 416.0,
 415.0,
 416.0,
 416.0,
 415.0,
 418.0,
 416.0,
 415.0,
 416.0,
 415.0,
 419.0,
 415.0,
 416.0,
 416.0,
 418.0,
 417.0,
 415.0,
 418.0,
 416.0,
 418.0,
 415.0,
 416.0,
 415.0,
 418.0,
 418.0,
 419.0,
 417.0,
 416.0,
 417.0,
 416.0,
 415.0,
 419.0,
 418.0,
 417.0,
 416.0,
 416.0,
 417.0,
 416.0,
 416.0,
 415.0,
 416.0,
 416.0,
 416.0,
 416.0,
 415.0,
 415.0,
 416.0,
 415.0,
 415.0,
 416.0,
 418.0,
 418.0,
 416.0,
 418.0,
 416.0,
 416.0,
 416.0,
 418.0,
 415.0,
 416.0,
 419.0,
 416.0,
 416.0,
 416.0,
 418.0,
 415.0,
 416.0,
 416.0,
 418.0,
 415.0,
 418.0,
 416.0,
 416.0,
 416.0,
 416.0,
 415.0,
 419.0,
 416.0,
 416.0,
 416.0,
 416.0,
 417.0,
 416.0,
 416.0,
 417.0,
 415.0,
 416.0,
 418.0,
 416.0,
 417.0,
 416.0,
 416.0,
 415.0,
 416.0,
 416.0,
 416.0,
 416.0,
 415.0,
 417.0,
 416.0,
 416.0,
 416.0,
 416.0,
 415.0,
 416.0,
 414.0,
 416.0,
 416.0,
 416.0,
 415.0,
 416.0,
 415.0,
 419.0,
 415.0,
 417.0,
 417.0,
 416.0,
 415.0,
 415.0,
 415.0,
 416.0,
 416.0,
 416.0,
 416.0,
 416.0,
 416.0,
 416.0,
 415.0,
 416.0,
 417.0,
 0.0,
 402.0,
 401.0,
 403.0,
 404.0,
 407.0,
 404.0,
 404.0,
 405.0,
 405.0,
 403.0,
 405.0,
 405.0,
 402.0,
 406.0,
 405.0,
 404.0,
 407.0,
 407.0,
 406.0,
 404.0,
 405.0,
 405.0,
 407.0,
 406.0,
 386.0,
 386.0,
 387.0,
 386.0,
 384.0,
 386.0,
 384.0,
 386.0,
 387.0,
 387.0,
 386.0,
 386.0,
 0.0,
 0.0,
 0.0,
 421.0,
 421.0,
 425.0,
 424.0,
 423.0,
 425.0,
 427.0,
 425.0,
 426.0,
 426.0,
 427.0,
 429.0,
 429.0,
 427.0,
 425.0,
 429.0,
 428.0,
 426.0,
 425.0,
 427.0,
 428.0,
 430.0,
 430.0,
 431.0,
 429.0,
 429.0,
 429.0,
 429.0,
 428.0,
 429.0,
 432.0,
 428.0,
 430.0,
 431.0,
 430.0,
 431.0,
 429.0,
 430.0,
 428.0,
 430.0,
 429.0,
 431.0,
 429.0,
 429.0,
 430.0,
 427.0,
 429.0,
 431.0,
 432.0,
 429.0,
 432.0,
 430.0,
 428.0,
 430.0,
 427.0,
 432.0,
 430.0,
 432.0,
 430.0,
 432.0,
 430.0,
 427.0,
 430.0,
 427.0,
 429.0,
 429.0,
 426.0,
 428.0,
 430.0,
 428.0,
 432.0,
 429.0,
 430.0,
 432.0,
 432.0,
 429.0,
 432.0,
 428.0,
 429.0,
 432.0,
 430.0,
 430.0,
 432.0,
 431.0,
 431.0,
 432.0,
 431.0,
 432.0,
 429.0,
 432.0,
 432.0,
 432.0,
 429.0,
 429.0,
 432.0,
 432.0,
 433.0,
 429.0,
 430.0,
 432.0,
 432.0,
 431.0,
 430.0,
 429.0,
 432.0,
 432.0,
 430.0,
 431.0,
 430.0,
 434.0,
 434.0,
 432.0,
 431.0,
 433.0,
 431.0,
 432.0,
 429.0,
 430.0,
 430.0,
 431.0,
 432.0,
 430.0,
 434.0,
 429.0,
 430.0,
 432.0,
 432.0,
 431.0,
 432.0,
 430.0,
 429.0,
 432.0,
 433.0,
 431.0,
 430.0,
 434.0,
 430.0,
 432.0,
 433.0,
 427.0,
 432.0,
 433.0,
 431.0,
 432.0,
 432.0,
 430.0,
 431.0,
 431.0,
 430.0,
 430.0,
 430.0,
 430.0,
 430.0,
 433.0,
 430.0,
 432.0,
 430.0,
 432.0,
 429.0,
 432.0,
 432.0,
 432.0,
 431.0,
 432.0,
 431.0,
 433.0,
 430.0,
 431.0,
 429.0,
 432.0,
 431.0,
 434.0,
 432.0,
 429.0,
 433.0,
 430.0,
 433.0,
 431.0,
 429.0,
 427.0,
 431.0,
 430.0,
 429.0,
 432.0,
 431.0,
 428.0,
 430.0,
 430.0,
 432.0,
 432.0,
 430.0,
 430.0,
 431.0,
 428.0,
 430.0,
 430.0,
 432.0,
 434.0,
 430.0,
 431.0,
 428.0,
 430.0,
 431.0,
 429.0,
 429.0,
 430.0,
 429.0,
 432.0,
 433.0,
 431.0,
 429.0,
 434.0,
 431.0,
 431.0,
 432.0,
 432.0,
 429.0,
 430.0,
 429.0,
 430.0,
 432.0,
 430.0,
 432.0,
 433.0,
 430.0,
 430.0,
 433.0,
 432.0,
 431.0,
 434.0,
 433.0,
 430.0,
 432.0,
 433.0,
 432.0,
 430.0,
 432.0,
 431.0,
 429.0,
 432.0,
 432.0,
 432.0,
 430.0,
 429.0,
 431.0,
 432.0,
 431.0,
 432.0,
 432.0,
 431.0,
 430.0,
 432.0,
 430.0,
 429.0,
 432.0,
 434.0,
 432.0,
 430.0,
 433.0,
 431.0,
 430.0,
 432.0,
 430.0,
 430.0,
 432.0,
 433.0,
 432.0,
 433.0,
 430.0,
 431.0,
 430.0,
 432.0,
 430.0,
 430.0,
 430.0,
 430.0,
 434.0,
 432.0,
 430.0,
 431.0,
 431.0,
 430.0,
 430.0,
 434.0,
 432.0,
 433.0,
 432.0,
 430.0,
 432.0,
 430.0,
 431.0,
 433.0,
 432.0,
 430.0,
 430.0,
 430.0,
 430.0,
 431.0,
 431.0,
 430.0,
 432.0,
 430.0,
 430.0,
 433.0,
 431.0,
 430.0,
 430.0,
 430.0,
 431.0,
 429.0,
 430.0,
 434.0,
 433.0,
 430.0,
 434.0,
 431.0,
 431.0,
 432.0,
 432.0,
 431.0,
 430.0,
 430.0,
 432.0,
 430.0,
 431.0,
 430.0,
 432.0,
 430.0,
 432.0,
 65535.0,
 65535.0,
 65535.0,
 65535.0,
 65535.0,
 430.0,
 430.0,
 433.0,
 433.0,
 433.0,
 433.0,
 435.0,
 431.0,
 433.0,
 431.0,
 432.0,
 432.0,
 430.0,
 432.0,
 430.0,
 432.0,
 434.0,
 430.0,
 434.0,
 430.0,
 433.0,
 430.0,
 434.0,
 430.0,
 429.0,
 429.0,
 432.0,
 430.0,
 433.0,
 432.0,
 434.0,
 431.0,
 432.0,
 433.0,
 433.0,
 430.0,
 430.0,
 430.0,
 431.0,
 431.0,
 432.0,
 434.0,
 434.0,
 429.0,
 430.0,
 429.0,
 430.0,
 430.0,
 430.0,
 432.0,
 432.0,
 434.0,
 431.0,
 433.0,
 432.0,
 434.0,
 430.0,
 430.0,
 430.0,
 430.0,
 433.0,
 431.0,
 434.0,
 429.0,
 432.0,
 432.0,
 431.0,
 432.0,
 430.0,
 430.0,
 431.0,
 432.0,
 432.0,
 432.0,
 430.0,
 432.0,
 434.0,
 434.0,
 432.0,
 434.0,
 432.0,
 431.0,
 429.0,
 429.0,
 430.0,
 432.0,
 433.0,
 430.0,
 434.0,
 429.0,
 432.0,
 429.0,
 430.0,
 432.0,
 431.0,
 430.0,
 432.0,
 433.0,
 434.0,
 430.0,
 429.0,
 430.0,
 433.0,
 432.0,
 430.0,
 430.0,
 432.0,
 431.0,
 432.0,
 430.0,
 433.0,
 431.0,
 434.0,
 432.0,
 432.0,
 432.0,
 432.0,
 433.0,
 431.0,
 430.0,
 430.0,
 431.0,
 429.0,
 430.0,
 430.0,
 432.0,
 431.0,
 432.0,
 432.0,
 432.0,
 430.0,
 430.0,
 432.0,
 432.0,
 434.0,
 432.0,
 430.0,
 430.0,
 432.0,
 432.0,
 434.0,
 433.0,
 431.0,
 432.0,
 432.0,
 430.0,
 432.0,
 430.0,
 433.0,
 430.0,
 432.0,
 432.0,
 429.0,
 433.0,
 432.0,
 431.0,
 431.0,
 431.0,
 431.0,
 432.0,
 430.0,
 432.0,
 434.0,
 434.0,
 430.0,
 432.0,
 433.0,
 434.0,
 432.0,
 433.0,
 432.0,
 432.0,
 432.0,
 430.0,
 432.0,
 432.0,
 431.0,
 433.0,
 431.0,
 433.0,
 432.0,
 431.0,
 432.0,
 434.0,
 431.0,
 432.0,
 434.0,
 434.0,
 432.0,
 434.0,
 431.0,
 434.0,
 434.0,
 432.0,
 434.0,
 432.0,
 431.0,
 434.0,
 432.0,
 432.0,
 434.0,
 432.0,
 431.0,
 434.0,
 433.0,
 434.0,
 431.0,
 432.0,
 432.0,
 432.0,
 432.0,
 432.0,
 434.0,
 434.0,
 433.0,
 432.0,
 432.0,
 431.0,
 432.0,
 435.0,
 432.0,
 432.0,
 432.0,
 432.0,
 433.0,
 432.0,
 434.0,
 433.0,
 434.0,
 434.0,
 435.0,
 434.0,
 432.0,
 434.0,
 432.0,
 432.0,
 435.0,
 431.0,
 432.0,
 434.0,
 434.0,
 432.0,
 434.0,
 431.0,
 431.0,
 432.0,
 433.0,
 434.0,
 434.0,
 432.0,
 432.0,
 434.0,
 435.0,
 434.0,
 432.0,
 432.0,
 435.0,
 434.0,
 431.0,
 434.0,
 431.0,
 433.0,
 432.0,
 430.0,
 435.0,
 432.0,
 435.0,
 435.0,
 430.0,
 434.0,
 433.0,
 435.0,
 434.0,
 431.0,
 434.0,
 432.0,
 435.0,
 435.0,
 430.0,
 434.0,
 430.0,
 432.0,
 432.0,
 432.0,
 434.0,
 434.0,
 435.0,
 434.0,
 434.0,
 434.0,
 434.0,
 431.0,
 434.0,
 ...]

In [236]:
for i in range(len(lst)):
    if (lst[i]>80 or lst[i]<-40 or lst1[i]<0 or lst1[i]>100 or lst2[i]>9):
        sensor= sensor.drop(index=i)

In [237]:
sensor.reset_index(inplace=True, drop=True)
sensor

,Temperature,Moisture,Nitrogen,Phosphorous,Potassium,pH,ElectricalConductivity
0,23.9,0.0,0.0,0.0,0.0,7.0,0.0
1,23.6,13.7,26.0,36.0,73.0,7.0,369.0
2,23.6,13.8,26.0,36.0,73.0,7.0,369.0
3,23.6,13.6,26.0,36.0,73.0,7.0,366.0
4,23.6,13.7,26.0,36.0,73.0,7.0,369.0
...,...,...,...,...,...,...,...
2121,25.1,4.7,17.0,24.0,48.0,7.0,238.0
2122,25.1,4.8,17.0,24.0,48.0,7.0,240.0
2123,25.1,4.9,17.0,24.0,47.0,7.0,240.0
2124,25.1,4.7,17.0,24.0,47.0,7.0,242.0
2125,25.1,4.6,17.0,23.0,47.0,7.0,236.0

# Crop Recommendation System #

In [238]:
crop=pd.read_csv('CropData.csv')
crop=crop[['N', 'P', 'K', 'temperature', 'humidity', 'ph',
       'rainfall', 'Sand%', 'Clay%', 'Silt%', 'label']]
crop

,N,P,K,temperature,humidity,ph,rainfall,Sand%,Clay%,Silt%,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,31.941176,39.764706,28.294118,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,31.348837,37.906977,30.744186,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,29.000000,33.040000,37.960000,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,31.941176,39.764706,28.294118,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,29.000000,33.040000,37.960000,rice
...,...,...,...,...,...,...,...,...,...,...,...
2099,107,34,32,26.774637,66.413269,6.780064,177.774507,31.941176,39.764706,28.294118,coffee
2100,99,15,27,27.417112,56.636362,6.086922,127.924610,33.978378,35.481081,30.540541,coffee
2101,118,33,30,24.131797,67.225123,6.362608,173.322839,33.978378,35.481081,30.540541,coffee
2102,117,32,34,26.272418,52.127394,6.758793,127.175293,31.941176,39.764706,28.294118,coffee
2103,104,18,30,23.603016,60.396475,6.779833,140.937041,31.941176,39.764706,28.294118,coffee

In [239]:
crop.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'Sand%',
       'Clay%', 'Silt%', 'label'],
      dtype='object')

In [240]:
crop=crop[['N', 'P', 'K', 'temperature', 'ph', 'rainfall','label']]

In [241]:
crop

        N   P   K  temperature        ph    rainfall   label
0      90  42  43    20.879744  6.502985  202.935536    rice
1      85  58  41    21.770462  7.038096  226.655537    rice
2      60  55  44    23.004459  7.840207  263.964248    rice
3      74  35  40    26.491096  6.980401  242.864034    rice
4      78  42  42    20.130175  7.628473  262.717340    rice
...   ...  ..  ..          ...       ...         ...     ...
2099  107  34  32    26.774637  6.780064  177.774507  coffee
2100   99  15  27    27.417112  6.086922  127.924610  coffee
2101  118  33  30    24.131797  6.362608  173.322839  coffee
2102  117  32  34    26.272418  6.758793  127.175293  coffee
2103  104  18  30    23.603016  6.779833  140.937041  coffee

[2104 rows x 7 columns]

Changing Rainfall column to Moisture!

In [242]:
crop.rename(columns = {'rainfall':'Moisture','N':'Nitrogen','P':'Phosphorous','K':'Potassium','ph':'pH','temperature':'Temperature'}, inplace = True)

C:\Users\Sasha\AppData\Local\Temp\ipykernel_9204\2982699543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crop.rename(columns = {'rainfall':'Moisture','N':'Nitrogen','P':'Phosphorous','K':'Potassium','ph':'pH','temperature':'Temperature'}, inplace = True)

In [243]:
crop

,Nitrogen,Phosphorous,Potassium,Temperature,pH,Moisture,label
0,90,42,43,20.879744,6.502985,202.935536,rice
1,85,58,41,21.770462,7.038096,226.655537,rice
2,60,55,44,23.004459,7.840207,263.964248,rice
3,74,35,40,26.491096,6.980401,242.864034,rice
4,78,42,42,20.130175,7.628473,262.717340,rice
...,...,...,...,...,...,...,...
2099,107,34,32,26.774637,6.780064,177.774507,coffee
2100,99,15,27,27.417112,6.086922,127.924610,coffee
2101,118,33,30,24.131797,6.362608,173.322839,coffee
2102,117,32,34,26.272418,6.758793,127.175293,coffee
2103,104,18,30,23.603016,6.779833,140.937041,coffee

In [244]:
X=crop[['Temperature','Moisture','Nitrogen', 'Phosphorous', 'Potassium','pH']]

In [245]:
Y=crop['label']

In [246]:
sensor.columns

Index(['Temperature', 'Moisture', 'Nitrogen', 'Phosphorous', 'Potassium', 'pH',
       'ElectricalConductivity'],
      dtype='object')

In [247]:
sensor=sensor[['Temperature','Moisture','Nitrogen', 'Phosphorous', 'Potassium','pH']]
sensor

     Temperature  Moisture  Nitrogen  Phosphorous  Potassium   pH
0           23.9       0.0       0.0          0.0        0.0  7.0
1           23.6      13.7      26.0         36.0       73.0  7.0
2           23.6      13.8      26.0         36.0       73.0  7.0
3           23.6      13.6      26.0         36.0       73.0  7.0
4           23.6      13.7      26.0         36.0       73.0  7.0
...          ...       ...       ...          ...        ...  ...
2121        25.1       4.7      17.0         24.0       48.0  7.0
2122        25.1       4.8      17.0         24.0       48.0  7.0
2123        25.1       4.9      17.0         24.0       47.0  7.0
2124        25.1       4.7      17.0         24.0       47.0  7.0
2125        25.1       4.6      17.0         23.0       47.0  7.0

[2126 rows x 6 columns]

In [248]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2)

In [249]:
X_train

      Temperature    Moisture  Nitrogen  Phosphorous  Potassium        pH
1990    26.508387  152.980170        72           41         36  6.065898
976     28.983334  109.022564        95           75         45  5.829899
1477    23.881246  104.911666         7          141        195  5.514253
1568    20.489545  111.839195        19           24         15  7.137137
1125    20.420948   66.930657        38          132        197  5.931102
...           ...         ...       ...          ...        ...       ...
1201    27.237083   70.425089         6          142        202  6.224543
1029    35.990097   95.371348        11           36         33  5.978634
1000    25.449262  100.661917       118           88         51  6.201912
1929    24.394595  197.122005        76           56         39  6.551130
1748    29.869083  192.767857        28           10         30  6.305741

[1683 rows x 6 columns]

In [250]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train_sc= mms.fit_transform(X_train)

X_test_sc = mms.transform(X_test)

SVM Classifier

In [251]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train_sc, Y_train)
clf.score(X_test_sc,Y_test)

0.9002375296912114

DTC Classifier

In [252]:
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier(random_state=42).fit(X_train_sc, Y_train)
dtc.score(X_test_sc,Y_test)

0.9429928741092637

Gradient Boosting Classifier

In [253]:
from sklearn.ensemble import GradientBoostingClassifier
grad = GradientBoostingClassifier()
grad.fit(X_train_sc, Y_train)

print('Gradient Boosting accuracy : {}'.format(grad.score(X_test_sc,Y_test)))

Gradient Boosting accuracy : 0.9643705463182898

Random Forest Classifier

In [254]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=14,n_estimators=1000)
rfc.fit(X_train_sc, Y_train)
rfc.score(X_test_sc, Y_test)

0.9762470308788599

In [255]:

print('RF Accuracy on training set: ',rfc.score(X_train_sc, Y_train))
print('RF Accuracy on test set: ',rfc.score(X_test_sc, Y_test))

RF Accuracy on training set:  0.9994058229352347
RF Accuracy on test set:  0.9762470308788599

In [256]:
sensor.columns

Index(['Temperature', 'Moisture', 'Nitrogen', 'Phosphorous', 'Potassium',
       'pH'],
      dtype='object')

In [257]:
input=pd.read_csv("input.csv",header=None)

In [258]:
input.columns=['Temperature', 'Moisture', 'Nitrogen', 'Phosphorous', 'Potassium',
       'pH', 'Electric Conductivity']

In [259]:
X_exp=input.iloc[:,0:6]
X_exp

   Temperature  Moisture  Nitrogen  Phosphorous  Potassium  pH
0         26.2       2.1         2            3          7   7

In [260]:
X_exp_sc=mms.transform(X_exp)

In [261]:
X_train

      Temperature    Moisture  Nitrogen  Phosphorous  Potassium        pH
1990    26.508387  152.980170        72           41         36  6.065898
976     28.983334  109.022564        95           75         45  5.829899
1477    23.881246  104.911666         7          141        195  5.514253
1568    20.489545  111.839195        19           24         15  7.137137
1125    20.420948   66.930657        38          132        197  5.931102
...           ...         ...       ...          ...        ...       ...
1201    27.237083   70.425089         6          142        202  6.224543
1029    35.990097   95.371348        11           36         33  5.978634
1000    25.449262  100.661917       118           88         51  6.201912
1929    24.394595  197.122005        76           56         39  6.551130
1748    29.869083  192.767857        28           10         30  6.305741

[1683 rows x 6 columns]

In [262]:
predict_crop=rfc.predict(X_exp_sc)

In [263]:
predict_crop[0]

'muskmelon'

In [264]:
# file = open("output.txt","a")
# file.writelines("a")
# file.writelines("a")
# file.close()

Sensor Dataset with Crop

In [265]:
sensor_crop=sensor.copy()

In [266]:
# sensor_crop['crop']=predict_crop

In [267]:
# sensor_crop

In [268]:
# sum=0
# for i in range(len(sensor_crop)):
#     if (sensor_crop['crop'][i]=='muskmelon'):
#         sum+=1
# print("Muskmelon has the highest count of crop predicted: ", sum)

# Fertilizer Recommendation System #

In [269]:
ferti=pd.read_csv("FertilizerData.csv")

In [270]:
ferti

,Unnamed: 0,Temperature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,0,26,52,38,Sandy,Maize,37,0,0,Urea
1,1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,3,32,62,34,Red,Tobacco,22,0,20,28-28
4,4,28,54,46,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...,...
94,94,25,50,32,Clayey,Pulses,24,0,19,28-28
95,95,30,60,27,Red,Tobacco,4,17,17,10-26-26
96,96,38,72,51,Loamy,Wheat,39,0,0,Urea
97,97,36,60,43,Sandy,Millets,15,0,41,DAP
98,98,29,58,57,Black,Sugarcane,12,0,10,20-20

Removing 'Humidity' and 'Soil Type' column

In [271]:
ferti=ferti[['Temperature', 'Moisture',
       'Crop Type', 'Nitrogen', 'Phosphorous', 'Potassium', 'Fertilizer Name']]

In [272]:
ferti

,Temperature,Moisture,Crop Type,Nitrogen,Phosphorous,Potassium,Fertilizer Name
0,26,38,Maize,37,0,0,Urea
1,29,45,Sugarcane,12,36,0,DAP
2,34,62,Cotton,7,30,9,14-35-14
3,32,34,Tobacco,22,20,0,28-28
4,28,46,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...
94,25,32,Pulses,24,19,0,28-28
95,30,27,Tobacco,4,17,17,10-26-26
96,38,51,Wheat,39,0,0,Urea
97,36,43,Millets,15,41,0,DAP
98,29,57,Sugarcane,12,10,0,20-20

In [273]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ferti['Crop Type']=le.fit_transform(ferti['Crop Type'])

C:\Users\Sasha\AppData\Local\Temp\ipykernel_9204\4286362767.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ferti['Crop Type']=le.fit_transform(ferti['Crop Type'])

In [274]:
ferti.columns

Index(['Temperature', 'Moisture', 'Crop Type', 'Nitrogen', 'Phosphorous',
       'Potassium', 'Fertilizer Name'],
      dtype='object')

In [275]:
x = ferti[['Temperature', 'Moisture', 'Nitrogen', 'Phosphorous',
       'Potassium','Crop Type']]

In [276]:
y = ferti['Fertilizer Name']

In [277]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2)

In [278]:
x_train_sc=mms.fit_transform(x_train)
x_train_sc

array([[0.61538462, 0.15      , 0.23684211, 0.92857143, 0.        ,
        0.2       ],
       [0.92307692, 0.3       , 0.21052632, 0.97619048, 0.        ,
        0.6       ],
       [0.53846154, 0.225     , 0.28947368, 0.88095238, 0.        ,
        0.2       ],
       [0.84615385, 0.2       , 0.23684211, 0.33333333, 0.        ,
        0.5       ],
       [0.07692308, 0.25      , 0.21052632, 0.30952381, 0.52631579,
        0.        ],
       [0.15384615, 0.85      , 0.15789474, 0.35714286, 0.        ,
        0.8       ],
       [0.23076923, 0.325     , 0.94736842, 0.        , 0.        ,
        0.7       ],
       [0.30769231, 0.425     , 0.13157895, 0.52380952, 0.52631579,
        0.6       ],
       [0.23076923, 0.        , 0.13157895, 0.71428571, 0.52631579,
        0.3       ],
       [1.        , 0.65      , 0.92105263, 0.        , 0.        ,
        1.        ],
       [0.23076923, 0.45      , 0.15789474, 0.69047619, 0.42105263,
        0.6       ],
       [0.61538462, 0.65      , 0.02631579, 0.69047619, 0.47368421,
        0.3       ],
       [0.30769231, 0.675     , 0.23684211, 0.85714286, 0.        ,
        1.        ],
       [0.38461538, 0.9       , 0.10526316, 0.73809524, 0.52631579,
        0.1       ],
       [0.69230769, 0.575     , 0.5       , 0.45238095, 0.        ,
        1.        ],
       [0.23076923, 0.4       , 0.84210526, 0.        , 0.        ,
        0.6       ],
       [0.69230769, 0.7       , 0.21052632, 0.28571429, 0.73684211,
        0.8       ],
       [0.15384615, 0.075     , 0.23684211, 0.95238095, 0.        ,
        0.7       ],
       [0.07692308, 0.15      , 0.26315789, 0.97619048, 0.        ,
        0.2       ],
       [0.38461538, 0.55      , 0.21052632, 1.        , 0.        ,
        0.        ],
       [0.        , 0.175     , 0.52631579, 0.45238095, 0.        ,
        0.7       ],
       [0.30769231, 0.125     , 0.23684211, 0.38095238, 0.89473684,
        0.9       ],
       [0.38461538, 0.025     , 0.10526316, 0.71428571, 0.47368421,
        0.5       ],
       [0.15384615, 0.45      , 0.5       , 0.57142857, 0.        ,
        0.4       ],
       [0.        , 0.025     , 0.28947368, 0.26190476, 0.73684211,
        0.2       ],
       [0.30769231, 0.9       , 0.18421053, 0.9047619 , 0.        ,
        0.1       ],
       [0.30769231, 0.3       , 0.10526316, 0.35714286, 0.        ,
        0.4       ],
       [0.53846154, 0.225     , 0.47368421, 0.47619048, 0.        ,
        0.9       ],
       [0.07692308, 0.575     , 0.5       , 0.45238095, 0.        ,
        1.        ],
       [0.15384615, 0.225     , 1.        , 0.        , 0.        ,
        0.5       ],
       [0.07692308, 0.275     , 0.26315789, 0.30952381, 0.        ,
        0.7       ],
       [1.        , 0.575     , 0.10526316, 0.66666667, 0.42105263,
        1.        ],
       [0.76923077, 0.425     , 0.15789474, 0.83333333, 0.        ,
        0.        ],
       [0.69230769, 0.5       , 0.05263158, 0.5       , 1.        ,
        0.6       ],
       [0.84615385, 0.925     , 0.28947368, 0.95238095, 0.        ,
        0.1       ],
       [0.        , 0.375     , 0.05263158, 0.38095238, 1.        ,
        0.7       ],
       [0.15384615, 0.25      , 0.86842105, 0.        , 0.        ,
        0.5       ],
       [0.38461538, 0.1       , 0.97368421, 0.        , 0.        ,
        0.2       ],
       [0.69230769, 0.8       , 0.13157895, 0.30952381, 0.        ,
        0.8       ],
       [0.61538462, 0.625     , 0.97368421, 0.        , 0.        ,
        1.        ],
       [0.38461538, 0.475     , 0.15789474, 0.21428571, 0.        ,
        0.4       ],
       [0.46153846, 0.6       , 0.15789474, 0.33333333, 0.68421053,
        0.8       ],
       [0.84615385, 0.45      , 0.28947368, 0.97619048, 0.        ,
        0.4       ],
       [0.30769231, 0.75      , 0.10526316, 0.78571429, 0.42105263,
        0.8       ],
       [0.38461538, 0.05      , 0.21052632, 0.95238095, 0.        ,
        0.8       ],
       [0.69230769, 0.875     , 0.81578947, 0.        , 0.        ,
        0.8       ],
       [0.38461538, 0.425     , 0.44736842, 0.42857143, 0.        ,
        0.4       ],
       [0.30769231, 0.5       , 0.21052632, 0.85714286, 0.        ,
        0.8       ],
       [0.69230769, 0.325     , 0.92105263, 0.        , 0.        ,
        0.6       ],
       [0.23076923, 0.3       , 0.84210526, 0.        , 0.        ,
        0.4       ],
       [0.69230769, 0.15      , 0.5       , 0.5       , 0.        ,
        0.9       ],
       [0.38461538, 0.6       , 0.23684211, 0.21428571, 0.        ,
        1.        ],
       [0.69230769, 0.95      , 0.26315789, 0.9047619 , 0.        ,
        0.1       ],
       [0.69230769, 0.925     , 0.07894737, 0.71428571, 0.47368421,
        0.1       ],
       [0.23076923, 1.        , 0.92105263, 0.        , 0.        ,
        0.1       ],
       [0.53846154, 0.225     , 0.47368421, 0.57142857, 0.        ,
        0.9       ],
       [0.61538462, 0.35      , 0.23684211, 0.23809524, 0.        ,
        0.6       ],
       [0.46153846, 0.175     , 0.92105263, 0.        , 0.        ,
        0.9       ],
       [0.53846154, 0.125     , 0.89473684, 0.        , 0.        ,
        0.8       ],
       [0.38461538, 0.05      , 0.        , 0.4047619 , 0.89473684,
        0.9       ],
       [0.46153846, 0.95      , 0.18421053, 0.35714286, 0.63157895,
        0.1       ],
       [0.69230769, 0.975     , 0.52631579, 0.47619048, 0.        ,
        0.1       ],
       [0.38461538, 0.325     , 0.15789474, 0.33333333, 0.        ,
        0.4       ],
       [0.07692308, 0.275     , 0.07894737, 0.47619048, 0.84210526,
        0.7       ],
       [0.        , 0.975     , 0.13157895, 0.23809524, 0.        ,
        0.1       ],
       [0.30769231, 0.375     , 0.52631579, 0.54761905, 0.        ,
        0.2       ],
       [0.30769231, 0.2       , 0.13157895, 0.71428571, 0.36842105,
        0.5       ],
       [0.        , 0.775     , 0.18421053, 0.35714286, 0.68421053,
        0.8       ],
       [0.61538462, 0.225     , 0.89473684, 0.        , 0.        ,
        0.7       ],
       [0.07692308, 0.85      , 0.18421053, 0.21428571, 0.        ,
        0.8       ],
       [0.38461538, 0.825     , 0.15789474, 0.76190476, 0.36842105,
        0.8       ],
       [0.84615385, 0.4       , 0.97368421, 0.        , 0.        ,
        0.2       ],
       [0.76923077, 0.075     , 0.10526316, 0.73809524, 0.36842105,
        0.7       ],
       [0.15384615, 0.125     , 0.81578947, 0.        , 0.        ,
        0.4       ],
       [0.07692308, 0.35      , 0.44736842, 0.54761905, 0.        ,
        0.7       ],
       [0.30769231, 1.        , 0.26315789, 0.83333333, 0.        ,
        0.1       ],
       [0.38461538, 0.55      , 0.47368421, 0.5       , 0.        ,
        0.3       ],
       [0.        , 0.35      , 0.44736842, 0.45238095, 0.        ,
        0.        ],
       [0.23076923, 0.55      , 0.02631579, 0.35714286, 0.94736842,
        0.        ]])

In [279]:
x_test_sc=mms.transform(x_test)
x_test_sc

array([[0.        , 1.        , 0.84210526, 0.        , 0.        ,
        0.1       ],
       [0.30769231, 0.45      , 0.52631579, 0.42857143, 0.        ,
        0.6       ],
       [0.92307692, 0.175     , 0.21052632, 0.92857143, 0.        ,
        0.5       ],
       [0.84615385, 0.625     , 0.21052632, 0.45238095, 0.94736842,
        1.        ],
       [0.76923077, 0.2       , 0.18421053, 0.88095238, 0.        ,
        0.9       ],
       [0.23076923, 0.525     , 0.81578947, 0.        , 0.        ,
        0.6       ],
       [0.46153846, 0.575     , 0.26315789, 0.28571429, 0.78947368,
        0.3       ],
       [0.69230769, 0.725     , 0.89473684, 0.        , 0.        ,
        1.        ],
       [0.38461538, 0.375     , 0.97368421, 0.        , 0.        ,
        0.4       ],
       [0.38461538, 0.95      , 0.13157895, 0.69047619, 0.47368421,
        0.1       ],
       [0.53846154, 0.4       , 0.52631579, 0.52380952, 0.        ,
        0.6       ],
       [0.07692308, 0.175     , 0.21052632, 0.19047619, 0.        ,
        0.5       ],
       [0.30769231, 0.225     , 0.28947368, 0.88095238, 0.        ,
        0.4       ],
       [0.46153846, 0.475     , 0.44736842, 0.66666667, 0.        ,
        0.        ],
       [0.07692308, 0.475     , 0.5       , 0.47619048, 0.        ,
        0.3       ],
       [0.07692308, 0.325     , 0.86842105, 0.        , 0.        ,
        0.3       ],
       [0.84615385, 0.325     , 0.07894737, 0.71428571, 0.47368421,
        0.        ],
       [0.15384615, 0.125     , 0.23684211, 0.30952381, 0.        ,
        0.7       ],
       [0.30769231, 0.8       , 0.21052632, 0.23809524, 0.        ,
        0.8       ],
       [0.23076923, 0.25      , 0.97368421, 0.        , 0.        ,
        0.4       ]])

In [280]:
rfc.fit(x_train_sc,y_train)

RandomForestClassifier(max_depth=14, n_estimators=1000)

In [281]:
rfc.predict(x_test_sc)

array(['Urea', '28-28', 'DAP', '10-26-26', 'DAP', 'Urea', '17-17-17',
       'Urea', 'Urea', '14-35-14', '28-28', '20-20', 'DAP', '28-28',
       '28-28', 'Urea', '14-35-14', '20-20', '20-20', 'Urea'],
      dtype=object)

In [282]:
rfc.score(x_test,y_test)

c:\Python311\Lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

0.3

Removing pH Attribute

In [283]:
sensor=sensor[['Temperature', 'Moisture','Nitrogen', 'Phosphorous', 'Potassium']]

In [284]:
sensor

     Temperature  Moisture  Nitrogen  Phosphorous  Potassium
0           23.9       0.0       0.0          0.0        0.0
1           23.6      13.7      26.0         36.0       73.0
2           23.6      13.8      26.0         36.0       73.0
3           23.6      13.6      26.0         36.0       73.0
4           23.6      13.7      26.0         36.0       73.0
...          ...       ...       ...          ...        ...
2121        25.1       4.7      17.0         24.0       48.0
2122        25.1       4.8      17.0         24.0       48.0
2123        25.1       4.9      17.0         24.0       47.0
2124        25.1       4.7      17.0         24.0       47.0
2125        25.1       4.6      17.0         23.0       47.0

[2126 rows x 5 columns]

Taking Random input and crop name for Fertilizer prediction

In [285]:
user_crop=['Sugarcane', 'Millets', 'Cotton', 'Paddy', 'Wheat', 'Oil seeds', 'Ground Nuts', 'Pulses', 'Barley', 'Tobacco', 'Maize']

In [286]:
user_crop=le.transform(user_crop)

In [287]:
x_exp=input.iloc[:,0:5]
x_exp

   Temperature  Moisture  Nitrogen  Phosphorous  Potassium
0         26.2       2.1         2            3          7

In [288]:
x_exp['Crop Type']=user_crop[5]
x_exp

   Temperature  Moisture  Nitrogen  Phosphorous  Potassium  Crop Type
0         26.2       2.1         2            3          7          5

In [289]:
x_exp_sc=mms.transform(x_exp)

In [290]:
input_ferti=x_exp_sc

In [291]:
predict_ferti=rfc.predict(input_ferti)
predict_ferti[0]

'17-17-17'

Predicting the fertilizer with crops obtained earlier

In [292]:
sensor_crop

     Temperature  Moisture  Nitrogen  Phosphorous  Potassium   pH
0           23.9       0.0       0.0          0.0        0.0  7.0
1           23.6      13.7      26.0         36.0       73.0  7.0
2           23.6      13.8      26.0         36.0       73.0  7.0
3           23.6      13.6      26.0         36.0       73.0  7.0
4           23.6      13.7      26.0         36.0       73.0  7.0
...          ...       ...       ...          ...        ...  ...
2121        25.1       4.7      17.0         24.0       48.0  7.0
2122        25.1       4.8      17.0         24.0       48.0  7.0
2123        25.1       4.9      17.0         24.0       47.0  7.0
2124        25.1       4.7      17.0         24.0       47.0  7.0
2125        25.1       4.6      17.0         23.0       47.0  7.0

[2126 rows x 6 columns]

In [293]:
# def unique(list1):
 
#     # insert the list to the set
#     list_set = set(list1)
#     # convert the set to the list
#     unique_list = (list(list_set))
#     return unique_list

In [294]:
# a=sensor_crop['crop'].values

In [295]:
# print(unique(a))

In [296]:
# b=ferti['Crop Type'].values

In [297]:
# print(unique(b))

The crop sets doesn't match....